### ISSUE TITLE
找不到select_tags

### ISSUE THREAD

**Issue by kenyonxu** [laojingwei/comfy_assemble_tags_node#1]
用的最新版本，报错如下

----------start------第一次使用-------未发现select_tags文件夹，正在处理。。。
Traceback (most recent call last):
  File "D:\AIArt\ComfyUI\nodes.py", line 1205, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AIArt\ComfyUI\custom_nodes\comfy_assemble_tags_node\__init__.py", line 11, in <module>
    shutil.copytree (select_tags_path_bk, select_tags_path)
  File "C:\Users\kenyo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\AIArt\\ComfyUI\\ComfyUI\\custom_nodes\\comfy_assemble_tags_node\\select_tags'

**Comment by kenyonxu** [comment]
我用的不是standalone版本，后来仔细看了下init.py之后解决了问题，方案如下：

select_tags_path_bk = os.path.join(cwd, "ComfyUI", "custom_nodes", "comfy_assemble_tags_node", "select_tags")
↓
select_tags_path_bk = os.path.join(cwd, "custom_nodes", "comfy_assemble_tags_node", "select_tags")

**Comment by laojingwei** [comment]
实在抱歉，这段时间太忙没注意看信息，很高兴你解决了

**Comment by kenyonxu** [comment]
然而又出了新的问题233， 我进去comfyui之后select tags node上面没有选择tags的按钮，只有一个文本框

**Comment by laojingwei** [comment]
你能发下文件路径截图和comfyui界面添加tag截图等信息我看看吗？

**Comment by kenyonxu** [comment]
![image](https://user-images.githubusercontent.com/1241198/236091313-8d814ad5-bde6-4983-a74a-58481e7173f8.png)
![image](https://user-images.githubusercontent.com/1241198/236091416-c5067f5e-6cf5-47d0-9bbd-0bb8987702bf.png)
![image](https://user-images.githubusercontent.com/1241198/236091432-4e0da34e-a159-4550-9349-52f9eff6e3cb.png)

**Comment by laojingwei** [comment]
可能一些文件路径无法匹配到，把你项目放到github上，我下载下来跑一下，模型依赖什么的不要传了，太大了


***@***.***
 
发件人： Kai Xu
发送时间： 2023-05-04 09:49
收件人： laojingwei/comfy_assemble_tags_node
抄送： laojingwei; Comment
主题： Re: [laojingwei/comfy_assemble_tags_node] 找不到select_tags (Issue #1)

**Comment by kenyonxu** [comment]
好了这个我也解决了2333，也是路径问题
select_tags_path = os.path.join(cwd, "ComfyUI", "web", "extensions", "select_tags")
↓
select_tags_path = os.path.join(cwd, "web", "extensions", "select_tags")
作者大佬能不能针对git版和standalone版本的comfyui做一下路径检测？

**Comment by jtpan777** [comment]
感谢  试试了几次 ，好像明白了。
